### PR TITLE
InitConn --> IIPConnection, updated test run scripts, reverted statusString change

### PR DESCRIPTION
**Pull request by ComFreek**
1. I have now moved InitConn from utils.js into its own file `IIPConnection.js`. I hope the usage of the word IIP makes sense in this case, please correct me if I am wrong! In addition, IIPConnection and the new ProcessConnection (which was formerly called Connection) are now subclasses of Connection.

 ```
Connection
|-------------------------------------
|                                    |
ProcessConnection              IIPConnection
```

 The checks `conn.constructor == Utils.InitConn` have been replaced by `conn instanceof IIPConnection`. The latter is also less restrictive insofar that it would also allow subclasses of IIPConnection to pass the test.

2. `Merge remote-tracking branch 'upstream/master'` is a merge of your most recent changes into my code base.

3. `fbptests.bat` now automatically runs all fbptest[xy].js in the directory (=> specifying all test file names by hand is not necessary anymore!). It makes use of the command `forfiles`, which doesn't support an alphanumeric sort, so I had to rename all test files to be collected in the right order by `forfiles`.

4. `fbptests.sh` now also includes every available test.

5. @jpaulm It seems that you were working on an older code base when submitting [this line of code](https://github.com/jpaulm/jsfbp/commit/4abd3938473dac59975ec3f6b3c1cec1a1dcdf10#diff-168726dbe96b3ce427e7fedce31bb0bcR259). It obviously broke fbptest7 due to my recent change of `Process.statusString` to `(Process instance).getStatusString()`. I reverted this change. The command `git pull` should be able to keep your local code base always updated to the code base of your jsfbp GitHub repository. Run it preferably after every change you did or accept (e.g. a PR) online.

### CODE REVIEW

**Comment by jpaulm** [comment]
Don't understand 5 - however, as long as its works after the merge!

Noticed wsrecv was still following Tom's API - have fixed that - will
retest websockets...

Also, I think wsrecv and wsresp should be in components, not
examples/websockets...   Or possibly both!

I'll do the merge!

Cheers,

Paul

**Comment by jpaulm** [comment]
Done!  Thanks, @comfreek!

**Comment by ComFreek** [comment]
Thanks!
Re point 5: Maybe you missed [this change](https://github.com/jpaulm/jsfbp/commit/2a71befc18fb4c8f518d34ba8c56b815d2b3cf75). 

Frankly speaking, I've always forgotten to test the web socket example.

> Also, I think wsrecv and wsresp should be in components

:+1: Agree.

**Comment by jpaulm** [comment]
Have moved wsrecv and wsresp to components.

Regards,

Paul

**Pull request merged**
