### PR TITLE
Encapsulate and separeate Network and Runtime

### PR DESCRIPTION
**Pull request by ComFreek**
I have split index.js into two files (`core/Network.js` and `core/runtimes/FiberRuntime/index.js`). Both files encapsulate their functionality in classes, so that none of them is able to change global state. Every instance of a network created by *new* will be independent from other instances.

`fbptest01.js` now looks like:
```
var fbp = require('..');

// --- define network ---
var network = new fbp.Network();

var sender = network.defProc('./components/sender.js');
var copier = network.defProc('./components/copier.js');
var recvr  = network.defProc('./components/recvr.js');

network.initialize(sender, 'COUNT', '200');
network.connect(sender, 'OUT', copier, 'IN', 5);
network.connect(copier, 'OUT', recvr, 'IN', 5);

// --- run ---
var fiberRuntime = new fbp.FiberRuntime();
network.run(fiberRuntime, { trace: true });
```

The only design problem I still have is what the best option is to pass a Runtime object to InputPorts and OutputPorts. The current implementation calls the method `setPortRuntime` on every InputPort/OutputPort. As there is no easy way (I know) to get a list of all of them I have to traverse all processes, which is a highly inefficient action. @jpaulm Do you know of a better way?

```
Network.prototype.run = function(runtime, options, callback) {
  options = options || {};
  function setPortRuntime (port) {
    port[1].setRuntime(runtime);
  }
  this._processes.forEach(function (process) {
    process.inports.forEach(setPortRuntime);
    process.outports.forEach(setPortRuntime);
  });
  runtime.run(this._processes, options, callback || function(){});
};
```

### CODE REVIEW

**Comment by jpaulm** [comment]
Sorry @comfreek , what is a Runtime object?

**Comment by ComFreek** [comment]
@jpaulm A Runtime class provides the functionality to run an instance of a Network. At the moment we only have one runtime class and that is FiberRuntime.

Prior to this PR we only had `index.js` which contained the functionality for both the network and the runtime. Now the network and the runtime are encapsulated in classes.

**Comment by jpaulm** [comment]
Thanks, @comfreek , that's a bit clearer!   However, I didn't get the
connection between Runtime and input and output ports...

I did the Merge, but haven't had time to test it yet.

BTW - not sure where to post this...   I still can't run with the latest
node.js - at least before the last merge.  I remember you did something
with a special nodejs file - should I change the readme?

TIA

Paul

**Comment by ComFreek** [comment]
Let's take OutputPort.js: https://github.com/jpaulm/jsfbp/blob/7ac70884475f7d00806ca91d712d04f36c440fd0/core/OutputPort.js#L44 (this link refers to a version prior to the merge)

```
// line 44
this.queue.push(conn.down);
```
OutputPort pushes something to the queue to which it got access by accepting a queue object in its constructor (line 5).
A queue object doesn't make sense at the time of creating the network. It is only used when running the network. Therefore, it should be possible to inject the queue object at a later point of time (i.e. when one calls network.run()). Actually, there shouldn't even be runtime-related methods at the time of wiring the graph together.
Ideally, we would have no runtime-related functions in core files (except for runtimes/FiberRuntime/index.js of course). OutputPort.js includes Fibers ([line 1](https://github.com/jpaulm/jsfbp/blob/7ac70884475f7d00806ca91d712d04f36c440fd0/core/OutputPort.js#L2)) which breaks this rule.

At the time of executing the network's run command OutputPort and InputPort **must** have access to the queue object (or Runtime object which provides a method to add something to the queue). Therefore, the network must inject the Runtime object into each InputPort and OutputPort. <s>The problem is now to gain access to every InputPort and OutputPort. Currently the only way is to iterate `inports` and `outports` of every Process. This obviously results in many InputPorts/OutputPorts being assigned a Runtime twice.</s> Wait a moment, I had some errors in reasoning. Iterating every InputPort and OutputPort of a process should be perfectly fine, shouldn't it?

We will never be able to run this project with the latest Node.js unless we either drop Fiber or Fiber gets updated. Indeed I uploaded instructions on how to download and use an older Node.js Version: https://gist.github.com/ComFreek/c341bacfaae3aca887df

**Comment by jpaulm** [comment]
InPort and OutputPort need some way to notify waiting processes that they
can go...  In Java, you just say notify() wrt to an obect, and any thread
waiting on that object gets woken up...  That's basically what I had to
simulate...  Should be possible to o that with adequate separation.

Best regards to everyone,

Paul

**Pull request merged**
