### PR TITLE
Add initial implementation of collate (doesn't do brackets yet) and testing infrastructure

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by ComFreek** [comment]
:+1: for unit testing. However, since my PR #15 has been accepted `fbp.InputPort` no longer works. You have to use:
```
var InputPort = require('../core/InputPort');

...
```

**Comment by ComFreek** [comment]
I've done some further work on this:

- [x] 1. Implemented utils.js/Enum with a lookup map to ease Process#getStatusString()
       I also changed [Process.statusStrring](https://github.com/jpaulm/jsfbp/blob/9521c4f3f4b1f239369c90eba41f0ba676b0c105/core/Process.js#L27) to Process#getStatusString, i.e. it is now a member function.
- [x] 2. Removed gitignored file from index (examples/data/text_new.txt)
- [x] 3. Adjusted tests/collate component to split index.js, i.e. changing some files according to my comment above
- [x] 4. Added test for Enum
Actually, I was just reworking the Enum part when I thought that I could also fix this PR. Feel free to just pull in the relevant changes for point number 3.

**Comment by jpaulm** [comment]
Have merged your fork...  also removed the fbp. prefixes, as per @comfreek's comment.

Now how do I run your test?

Thanks

**Comment by jpaulm** [comment]
@comfreek What is the easiest way for me to pull in your 4 changes listed above prior to a Merge?  

Also, not sure what you meant by your point 3 above...?

**Comment by ComFreek** [comment]
> Also, not sure what you meant by your point 3 above...?

Please apologize my commit message which got too brief.

Prior to my changes to index.js you would have needed to write:
```
var fbp = require('..'); // assuming that the parent directory contains index.js

var somePort = new fbp.InputPort(...);
```
Now you must write:
```
var InputPort = require('../core/InputPort');

var somePort = new InputPort();
```
Basically, if you you are using something that is now contained in in the *core* directory, you need to update the code.

[Your latest commit](https://github.com/jpaulm/jsfbp/commit/89f959594e5764964848fccad6ef1c39c1434060) is only partially correct because you still have to include `var InputPort = require('../core/InputPort')`, for example. This is shown in the code sample above within this comment). Otherwise, InputPort (the same goes for InputPortArray and OutputPort) will be undefined.

You can just pull the latest changes from my fork:

1. `git clone https://github.com/ComFreek/jsfbp.git`
2. `npm install`
3. Test the changes

(Another option would be to add another remote to your current working directory of jsfbp - the directory you normally work in: `git add remote comfreek https://github.com/ComFreek/jsfbp.git`. Then execute `git fetch comfreek`, `git checkout master` (to ensure that you're on branch master) and `git merge comfreek/master`. But I suggest the way I outlined above, having multiple remotes and states can become quite confusing. Just using different directories is easier.)

**Comment by ComFreek** [comment]
@jpaulm In order to run @tlrobinson's tests have a look at [package.json](https://github.com/jpaulm/jsfbp/blob/19268d8a3407a92cb2fef85c762e2afa147fc1ee/package.json#L37).

```
"scripts": { 
  "test": "./node_modules/.bin/mocha --ui mocha-fibers --recursive -R spec --require test/test_helper.js" 
}
```
If you run the Node package Manager NPM `npm test`, that specific command will be run. Note that the syntax `npm [command]` only holds true for some specific command names (one of those is 'test'). You need `npm run-script [command]` for other command names (e.g. 'doc').

**Comment by jpaulm** [comment]
I installed mocha but now I'm getting
```
> jsfbp@0.1.0 test C:\Users\Paul\Documents\GitHub\FBP-Repos\jsfbp
> mocha --ui mocha-fibers --recursive -R spec --require test/test_helper.js

C:\Users\Paul\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:167
  if (!this._ui) throw new Error('invalid interface "' + name + '"');
                       ^
Error: invalid interface "mocha-fibers"
    at Mocha.ui (C:\Users\Paul\AppData\Roaming\npm\node_modules\mocha\lib\mocha.
js:167:24)
    at Object.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\mocha\
bin\_mocha:218:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```
@comfreek or @tlrobinson Help would be appreciated!

**Comment by ComFreek** [comment]
Did you forget to run `npm install` by any chance?

**Comment by ComFreek** [comment]
@jpaulm Re `collate.js`: `fbp.IP` must be replaced as well: https://github.com/jpaulm/jsfbp/blob/e808bf1a9f148d0229bd47626a69c87ca77d761d/components/collate.js#L13.

**Comment by jpaulm** [comment]
Sorry, @comfreek, missed that!  I figured @tlrobinson was going to make
those changes, but I wanted to pick up his Collate before he was ready to
do a merge.  I sort of understand Merge, but I don't really grok how to
pick up bits and pieces of other people's work, especially when they assume
an earlier API!

**Comment by jpaulm** [comment]
@comfreek, you're right - I did!  That's to pick up the latest package,
right?

@tlrobinson Could you change Collate, MockReceiver, etc. to use the correct
API calls (the ones that I specified at the beginning and which @comfreek
has restored).  I have tried to do them myself, but I am not clear what the
Mocks do!  I could probably figure them out, but you would be faster!

Thanks, both!

Paul

**Comment by tlrobinson** [comment]
MockSender is a simple component that sends IPs from a predefined JavaScript Array to it's "OUT" port, so that we can easily inject IPs into our test network. MockReciever is a simple component that records every IP it receives on it's "IN" port so we can verify the correct IPs were output from a certain process (in the correct order, if necessary). These components are probably mostly useful for writing tests.

For example, in this test I setup one senders which will send "1,m1", then "2,m2", etc, and one sender that sends "1,d11", then "1,d12", etc: https://github.com/tlrobinson/jsfbp/commit/19268d8a3407a92cb2fef85c762e2afa147fc1ee#diff-9d235979eb4cca9ec165984b63e48a0cR5

Then we setup a receiver which will write anything it receives to the `result` array here: https://github.com/tlrobinson/jsfbp/commit/19268d8a3407a92cb2fef85c762e2afa147fc1ee#diff-9d235979eb4cca9ec165984b63e48a0cR8

Then we setup the rest of the network including the `collate` component, and run it, then verify the `result` array is what we expect it to be here: https://github.com/tlrobinson/jsfbp/commit/19268d8a3407a92cb2fef85c762e2afa147fc1ee#diff-9d235979eb4cca9ec165984b63e48a0cR17

**Comment by jpaulm** [comment]
@tlrobinson  I have fixed up Collate and its test environment to match the new API.  Collate looks good!  And the test works!  

Please use the new API (what @comfreek calls the split index.js) for future work...  ;-) 

Thanks and best regards to both!

Paul

**Comment by ComFreek** [comment]
> @comfreek, you're right - I did!  That's to pick up the latest package,
right?

`npm install` installs all the dependencies (and dev-dependencies) listed in `package.json`. (The difference is that dev-dependencies shouldn't be needed to run the program. Mocha is certainly not required, whereas Fibers is!) The installed Node modules are saved in the folder `node_modules`. Whenever you delete that folder (e.g. by some Git commands to check out some other branch) or add a dependency which is not installed yet, you have to re-run `npm install`.

I am wondering why tlrobinson should have changed the API calls. I had already done this task at the time of writing comment 3 above. I have now re-merged your code base into mine: https://github.com/ComFreek/jsfbp
You can review the differences between my code base and yours by clicking compare on that page. You will get redirected to https://github.com/ComFreek/jsfbp/compare/jpaulm:master...master.

While re-merging the code bases I also got your error message &ndash; word-by-word! The problem was that I had used the old Node.js version.

**Comment by ComFreek** [comment]
> @comfreek, you're right - I did!  That's to pick up the latest package,
right?

`npm install` installs all the dependencies (and dev-dependencies) listed in `package.json`. (The difference is that dev-dependencies shouldn't be needed to run the program. Mocha is certainly not required, whereas Fibers is!) The installed Node modules are saved in the folder `node_modules`. Whenever you delete that folder (e.g. by some Git commands to check out some other branch) or add a dependency which is not installed yet, you have to re-run `npm install`.

I am wondering why tlrobinson should have changed the API calls. I had already done this task at the time of writing comment 3 above. I have now re-merged your code base into mine: https://github.com/ComFreek/jsfbp
You can review the differences between my code base and yours by clicking compare on that page. You will get redirected to https://github.com/ComFreek/jsfbp/compare/jpaulm:master...master.

While re-merging the code bases I also got your error message &ndash; word-by-word! The problem was that I had used the new Node.js version.

**Comment by jpaulm** [comment]
@comfreek , can I create a pull request for this stuff?   Not sure if
that's the right procedure...

Thx,

P.

**Comment by ComFreek** [comment]
Sure!
Do you see the big green button in [the comparison view between my and your codebase](https://github.com/ComFreek/jsfbp/compare/jpaulm:master...master)? Or do only I as the author of my forked repository see that?

**Comment by jpaulm** [comment]
I saw the button - I just wasn't sure if it was the *right* button!
Anyway, as you can see, I took the plunge!

Just ran a test and everything seems to work!  Including fbptest7 (!)

Thx,

Paul

**Pull request merged**
