### PR TITLE
Extract Enum into its own module to avoid circular dependencies

### PR DESCRIPTION
**Pull request by dancrumb**
So I pulled this out of utils because it's useful on its own without the other utils stuff.

I also found (in another branch) that pulling in utils from Process leads to a circular dependency. Extracting Enum helps avoid that

### CODE REVIEW

**Comment by jpaulm** [comment]
Should I delete the branch, or will you?

**Comment by dancrumb** [comment]
Once a branch is merged, feel free to delete it

**Comment by jpaulm** [comment]
Thanks!

Just did a `pull`.  Running `npm test`, I get 3 errors:

  1) breader should read a file and output its contents as bytes:

      Uncaught AssertionError: expected [ Array(13) ] to deeply equal [ Array(12
) ]
      + expected - actual

         111
         114
         108
         100
      -  13
         10
       ]

      at Assertion.assertEqual (C:\Users\Paul\Documents\GitHub\jsfbp\node_module
s\chai\lib\chai\core\assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (C:\Users\Paul\Documents\
GitHub\jsfbp\node_modules\chai\lib\chai\utils\addMethod.js:41:25)
      at C:\Users\Paul\Documents\GitHub\jsfbp\test\components\breader.js:19:30
      at C:\Users\Paul\Documents\GitHub\jsfbp\core\runtimes\FiberRuntime\index.j
s:104:5

  2) Network can load FBP components directly from modules:
     Uncaught SyntaxError: Cannot find module 'dummy-module'
      at require (internal/module.js:12:17)
      at loadComponent (C:\Users\Paul\Documents\GitHub\jsfbp\core\Network.js:34:
19)
      at Network.defProc (C:\Users\Paul\Documents\GitHub\jsfbp\core\Network.js:9
4:12)
      at Context.<anonymous> (C:\Users\Paul\Documents\GitHub\jsfbp\test\core\Net
work.js:22:27)
      at C:\Users\Paul\Documents\GitHub\jsfbp\node_modules\mocha-fibers\lib\moch
a-fibers.js:24:14

  3) Network can load FBP components that are part of a larger package:
     Uncaught SyntaxError: Cannot find module 'dummy-module'
      at require (internal/module.js:12:17)
      at loadComponent (C:\Users\Paul\Documents\GitHub\jsfbp\core\Network.js:34:
19)
      at Network.defProc (C:\Users\Paul\Documents\GitHub\jsfbp\core\Network.js:9
4:12)
      at Context.<anonymous> (C:\Users\Paul\Documents\GitHub\jsfbp\test\core\Net
work.js:29:27)
      at C:\Users\Paul\Documents\GitHub\jsfbp\node_modules\mocha-fibers\lib\moch
a-fibers.js:24:14


Are these expected?  TIA

**Comment by jpaulm** [comment]
PS Have to leave for the afternoon - looking forward to resuming later!  

Best regards

**Comment by dancrumb** [comment]
Aha...

So 1) is to do with line ending issues between Windows and *nix

2) and 3) are to do with some missing modules used for testing. I'll update `npm test` to run `npm install` first to make sure things are up to date

**Comment by dancrumb** [comment]
OK... those should be fixed when you pull master again

**Pull request merged**
