### PR TITLE
Feature/expose ip constants

### PR DESCRIPTION
**Pull request by dancrumb**
Expose the IP Types on the process object so that they're available to component designers without having to require them explicitly

### CODE REVIEW

**Comment by dancrumb** [comment]
FYI: There's no need to merge this. Once you're happy with it, you can close it.

This is one of the branches that I already merged

**Comment by jpaulm** [comment]
Closed!  However, npm test gives

  1) bwriter should write incoming IPs to a file:

      Uncaught AssertionError: expected 'Goodbye World\r\n' to equal
'Goodbye Wo
rld\n'
      + expected - actual

      -Goodbye World
      +Goodbye World

      at
C:\Users\Paul\Documents\GitHub\jsfbp\test\components\bwriter.js:41:25
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

I am never sure about /r and /n - they seem to vary between Windows and
Unix!

Regards,

Paul

**Comment by dancrumb** [comment]
OK - I think I have those fixed.

Also, I discovered appveyor, which is a Windows complement to Travis, so
I'll have a better chance to see these problems also.

**Comment by jpaulm** [comment]
Great! npm test passed with flying colours!

Best regards,

Paul

**Pull request closed without merging**
