### PR TITLE
Split index.js into core components

### PR DESCRIPTION
**Pull request by ComFreek**
**Ready to merge**

I've moved the rest of the todos to #16.
<hr>

- [x] Split index.js into core components
- [x] Coding style:
  - [x] Replaced CRLF by LF
  - [x] Added 'use strict' to all core/component files. I've left out the examples for brevity.
  - [x] Gitignore old-node compatibility stuff, i.e. [the files I created to use an older Node.js version](https://gist.github.com/ComFreek/c341bacfaae3aca887df). Admittedly, I was annoyed by the untracked files which had been always listed by `git status`.
 - [x] Consistent braces
 - [x] Consistent semicolons
 - [x] Replace `new Array` by `[]`. @jpaulm They are the same commands, but the latter is more idiomatic.

### CODE REVIEW

**Comment by ComFreek** [comment]
@jpaulm This is now ready to merge.

**Comment by jpaulm** [comment]
Replacing CRLF by LF?  That's odd - all my pushes up to now required CRLF
and failed if I had any LFs in the code ( use Windows7).  What's happening?!

Regards,

Paul

**Comment by ComFreek** [comment]
That's probably Git's `core.autocrlf` setting. You can change it as follows (I did the same):

1. Open cmd.exe and navigate to the project Folder
2. Type `git config core.autocrlf`, press <kbd>Enter</kbd>. You will probably see `true`.
3. Type `git config core.autocrlf false` to change it.
4. Repeat step 2 for verification purpose.

**Comment by jpaulm** [comment]
Thanks, I'll give that a try!

Regards

Paul

**Comment by ComFreek** [comment]
Maybe I should add that you most probably never got errors. You only get warnings, which inform you that LF will automatically be replaced by CR LF when committed.

**Comment by jpaulm** [comment]
No, I actually got a fail!  And I had to change the LFs manually - luckily
JujuEdit has a feature to do that!

**Comment by jpaulm** [comment]
I like the fact that my API is back where it was when I originally specified it!  Thanks!

**Pull request merged**
