### PR TITLE
Migrate the rest of examples and components

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by ComFreek** [comment]
FYI I'm currently doing a heavy refactoring based on this PR.

**Comment by jpaulm** [comment]
That's great, Tom!  Thanks so much!  I won't have time to work on this
until I get home this evening - but I'm looking forward to it!

I was just thinking - presumably there is a way to test these before I do
the merge...  Should I just do an install from your fork, or is there a
more formal way to do this?

Thanks,

Paul

**Comment by jpaulm** [comment]
@comfreek should you wait until @tlrobinson  has finished?  He still has a few component to move...

**Comment by ComFreek** [comment]
I thought he had finished &mdash; at least the title suggests that ("Migrate __the rest__ ..."). I am shortly before pushing my commits as well. <s>There is only one error left I cannot resolve.</s> Wait a moment, is `fbptest7.js` supposed to throw an exception? If so, the error I encountered is intentional.

**Comment by ComFreek** [comment]
@jpaulm By the way, I updated [my guide to use an old Node.js version](https://gist.github.com/ComFreek/c341bacfaae3aca887df) to include some more scripts, which are hopefully easier to use.

**Comment by tlrobinson** [comment]
Yes, this is complete.

I didn't look closely at fbptest7.js but I noticed that error as well, so I ran an older version and it also threw an error. I think it's demonstrating deadlock detection?

We should get some mocha tests running and up on Travis-CI to explicitly test these things.

**Comment by tlrobinson** [comment]
Oh I think @jpaulm was referring to moving some of the non-generic components to the examples directory (https://github.com/jpaulm/jsfbp/pull/9#issuecomment-73900708) but that shouldn't block you.

**Comment by ComFreek** [comment]
> I think it's demonstrating deadlock detection?

Yeah, I think the same. I agree, a unit testing framework should definitely be used (issue #7).

@jpaulm @tlrobinson Please have a look at my changes which got just pushed to my fork: https://github.com/ComFreek/jsfbp

TODO

- [x] Split index.js into several core files, see core Directory
  - [x] Adapted paths, requires and dependencies in components and examples.
         It was necessary to replace each occurrence of `fbp.IP` by `var IP = require('IP)` at the beginning of the file and `IP` in the specific line. The same goes for InputPort, OutputPort, InputPortArray, ...
  - [ ] Global state in `index.js`
    - [ ] Remove global variables `list` and `queue` in `index.js`. Since InputPort and OutputPort need them, I've made use of constructor dependency injection (basically `new InputPort(queue)` instead of `new InputPort()` in `index.js`).
    - [ ] Make each instance `fbp/index.js` unique.

What do you think? I can submit a PR for my changes if this PR gets accepted (because my changes are based on this PR).

**Comment by tlrobinson** [comment]
LGTM. A few nitpicks:

* I'm not a fan of "comma-first"/npm-style, but whatever.
* I'd only use `module.exports` when assigning it (`module.exports = `), otherwise `exports.whatever = ` is fine, but also not a big deal.
* We could aggregate the sub modules in `index.js`, e.x. `exports.IP = require('./core/ip')` etc, so the user just has to require one module.
* Regarding `list`/`queue`, it seems the only thing `Port`s and `Process`s do with them is push themselves onto it. Is there a reason not to just do something like the following in `index.js`:

```
var process = new Process(name || func.name, func);
list.push(process);
return process;
```

**Comment by tlrobinson** [comment]
Also, is there a reason methods like `initialize` and `connect` aren't on the Process object? A more idiomatic JavaScript API might look like this:

```
// --- define network ---
var flow = new Flow();

var sender = flow.createProc('./components/sender.js');
var copier = flow.createProc('./components/copier.js');
var recvr  = flow.createProc('./components/recvr.js');

sender.initialize('COUNT', '2000');
sender.connect('OUT', copier, 'IN', 5);
copier.connect('OUT', recvr, 'IN', 5);

flow.run({ trace: true });
```

(In that case the Process actually would need the "Flow" object injected in the constructor)

**Comment by ComFreek** [comment]
> •I'm not a fan of "comma-first"/npm-style, but whatever.
We should have coding style guidelines or adopt them from a third party. The indentation is sometimes wrong, fixing that shouldn't be at issue. I'd also advise to use `use strict` and brackets in IF statements. Personally I miss semicolons after function expressions (`InputPort.bla = function () {...};`) as well.

> •I'd only use  module.exports  when assigning it ( module.exports = ), otherwise  exports.whatever =  is fine, but also not a big deal.
Sure, but in my view consistency outweighs the terseness of `exports.whatver`.

> •We could aggregate the sub modules in  index.js , e.x.  exports.IP = require('./core/ip')  etc, so the user just has to require one module.
Must *the normal user* actually have access to `IP`, `InputPort`, ...? All the examples don't need these modules, so I think we should not expose them unless proven necessary.

> •Regarding  list / queue , it seems the only thing  Port s and  Process s do with them is push themselves onto it. Is there a reason not to just do something like the following in index.js :
I've seen some `push` commands in deeply nested if/for constructs, so I don't know whether it is actually possible to let index.js do the push operation. Consider `core/OutputPort.js#41` as an example which can't be easily translated to code in `index.js`.

:+1: to your API suggestion.

PS: I presume we stick to JS and don't switch to TypeScript, am I right?

**Comment by jpaulm** [comment]
Yup, fbptest7 is intended to demonstrate deadlock.

@tlrobinson or @comfreek, did you have any trouble with fbptest2?

BTW What does require ('..')  do?

Thanks,
P.

**Comment by jpaulm** [comment]
Can I assume the export name is same as file name?

Your connect is asymmetric - I would Reference to keep it symmetrical!

Thanks!

**Comment by ComFreek** [comment]
> @tlrobinson or @comfreek, did you have any trouble with fbptest2?
No, all tests (including fbptest7 after your confirmation) run fine with the code base I have.

> BTW What does require ('..')  do?
See here: http://stackoverflow.com/q/8364311/603003
Basically, it includes `index.js` from the parent directory.

> Can I assume the export name is same as file name?
What do you mean by 'export name'? Do you mean setting `module.exports.abc = ...`? You can set it to everything you want. You have to use the filename in the require call (`require('InputPort')`) though. Note that you can omit the .js file extension.

> Your connect is asymmetric - I would Reference to keep it symmetrical!
Could you clarify this? Do you refer to tlrobinson's example code above?

**Comment by tlrobinson** [comment]
@ComFreek Almost any style-guide beside's npm's is fine with me :) I skimmed Google's and Airbnb's and either would be fine, or we can just make our own and put it on the wiki. I generally just try to match existing style, but until it's consistent we should be more explicit.

+1 consistent indentation (seems like we're doing 2 spaces, not tabs)
+1 mandatory semicolons and braces
+1 "use strict"
-1 comma-first

> Must the normal user actually have access to IP, InputPort, ...? All the examples don't need these modules, so I think we should not expose them unless proven necessary.

If you're writing a component (which many people will do) then you need the Port and IP objects.

> Consider core/OutputPort.js#41 as an example which can't be easily translated to code in index.js.

Good point, though maybe we should inject the Network/Graph/Flow/FBP/whatever object instead of just the queue/list?

**Comment by jpaulm** [comment]
Sorry @comfreek, I was trying to use my Samsung tablet - very confusing!

1st 3 paras OK!

last para: yes, I was referring to @tlrobinson's code above.  And it should have said: 
"Your connect is asymmetric - I would prefer to keep it symmetrical!"

That's one of the things I don't like about OO - you have to apply methods to an object.  There are many cases where it is not obvious who is boss, so you pick one object and pass the other object as a parameter to the method.  You could equally well do it the other way round!  FBP is cooperative - no bosses! 

sender.initialize is a bit better, but it looks like you are initializing the sender, whereas you are in fact initializing the port, if anything.

Now that I have merged @tlrobinson's PR, do you have stuff waiting in the wings, as it were?

Regards,

Paul

**Comment by jpaulm** [comment]
@tlrobinson , I have merged your PR, for which many thanks, and my test cases are working again!

Except... how do I run fbptests.sh?  I assume it's some kind of shell...? 

Were you planning to move the test components to their own folder?

I will try to answer your other questions over the next day or so!

Regards,

Paul

**Comment by tlrobinson** [comment]
fbptests.sh a Unix/Linux/Mac shell script. It does the same thing as your .bat.

Yes I can move the test components but maybe I'll wait until @ComFreek is done with his current work.

**Comment by tlrobinson** [comment]
How about something like:

```
sender.inport('COUNT').initialize('2000');
fbp.connect(sender.outport('OUT'), copier.inport('IN'), 5);
fbp.connect(copier.outport('OUT'), recvr.inport('IN'), 5);
```

**Comment by jpaulm** [comment]
Sounds good.  Thanks!

Paul

**Comment by jpaulm** [comment]
I see what you are driving at.  However, inport and outport are redundant,
and some might find that they are unnecessary keystrokes!  I know Henri has
said that he likes to minimize keystrokes while coding in train stations!
:-)

Paul

**Comment by ComFreek** [comment]
@tlrobinson 

> Yes I can move the test components but maybe I'll wait until @ComFreek is done with his current work.

Thanks! I've just submitted my PR. You can already start working on my code base by adding a Git remote to my fork, but I'm sure you know that. See also #16 .

**Comment by ComFreek** [comment]
@tlrobinson 
Re
> And yes, we should definitely create an object encapsulating  list  and  queue  and any other global state (not sure what the name should be? "FBP", "Flow", "Graph", "Network") so that you can have multiple of them. So it'd look more like this:
><br>&mdash; [tlrobinson's comment above](https://github.com/jpaulm/jsfbp/pull/10#issuecomment-73958471)

I've just written a new test:
```
'use strict';
var fbp = require('../..');

describe('fbp', function() {
  it('should be able to connection a sender to a receiver', function() {
    var result = [];

    var sender = fbp.defProc(new MockSender([1,2,3,4,5]));
    var recvr  = fbp.defProc(new MockReceiver(result));

    fbp.connect(sender, 'OUT', recvr, 'IN', 5);
    fbp.run({ trace: false });
    
    expect(result).to.deep.equal([1,2,3,4,5]);    
  });
});
```
**And that test fails - if the collate.js test is also run**
A strange deadlock is detected:
```
Deadlock detected
- Process status: CLOSED -
- Process status: CLOSED -
- Process status: CLOSED - collate
- Process status: CLOSED -
- Process status: CLOSED -
- Process status: CLOSED -
```

If my test is run isolated from collate.js, everything works! They just don't work together due to the global state. This can be proven by inserting the following line above the `require('../..')` line:
```
delete require.cache[require.resolve('../..')];
```
If this line is inserted, everything works again!

**Comment by jpaulm** [comment]
Makes sense,  @comfreek and @tlrobinson !  I would suggest Network -
similar to JavaFBP and C#FBP.   And I think it should include 'count' as
well.

How would you package this?  Will it require another 'require'?  Or can
Network go in index.js?

And by the way, what is global.tracing?

Thx,

Paul

**Comment by ComFreek** [comment]
What is count?

<hr>

### Packaging index.js

I can see two possibilities to package index.js:

1. Set `module.exports` within index.js to the Network function/"class":

 ```
// index.js
var Network = module.exports = function () {
      // Please see my footnote concerning private variables
      this.processes = ...;
      this.queue = ...;
      this.list = ...;
};
Network.prototype.initialize = function () { ... };
Network.prototype.run = function () { ... };

// USAGE
// Assuming we use jsfbp as a Node module
// (i.e. somebody has installed jsfbp via `npm install jsfbp` [note: this wouldn't work since jsfbp isn't published yet])
var Network = require('fbp');
var myNetwork = new Network();
...
myNetwork.run();
```

2. Set `module.exports.Network` within index.js to the Network function:
 ```
// index.js
var Network = module.exports.Network = function () {
      // same as in the code sample above
};
// same as in the code sample above

// USAGE
var fbp = require('fbp');
var myNetwork = new fbp.Network(),
```

 One could even outsource the Network part:
 ```
// index.js
module.exports.Network = require('./core/network');
// same as in the code sample above
```

I would choose option 2 because of several advantages:

- From a user perspective, what would you think `require('fbp')` returns?
  Intuitively, I would say that the returned object provides functions and classes related to FBP. To put it differently, I wouldn't expect the require() call to directly return the Network constructor.
  
- Choosing option 2 provides more flexibility insofar that we can later safely expose more properties in index.js:

 ```
module.exports.Collate = require('./components/collate');

// USAGE
var fbp = require('fbp');
var myNetwork = new fbp.Network(); // still valid!
var myCollate = new fbp.Collate(); // also valid
```

 Doing this with option 1 is impossible. Eventually, we would need to switch to option 2, which constitutes a breaking change in the API!

- Elaborating the aforementioned advantage further leads us to exposing  all the standard components in index.js:

 ```
// index.js
module.exports.Components = {
      Collate: require('./components/collate'),
      Copier: require('./components/copier')
};
...

// USAGE
var fbp = require('fbp');
var myNetwork = new fbp.Network();

var collate = myNetwork.defProc(fbp.Components.Collate);
var copier = myNetwork.defProc(fbp.Components.Copier);
```

I am not sure whether exposing the core classes should be done. First, users which are using the standard components and the Network don't need core classes. Second, exposing them (so users potentially rely on them) prevents us from later doing breaking changes. Component developers need access to core classes, of course, but I feel granting this access should *not* happen in `index.js` (=our front-end to the outerworld &ndash; speaking as a module).

What do you both think?

<hr>
### global.tracing
Before my 'split index.js' changes `traces` was a simple local variable contained in and only used by `index.js`. Due to the split up into multiple files, we needed a means to share this variable. Variables declared in a usual way in a file are always local to this file - irrespective of the keyword `var`! Unfortunately, I said the converse in a comment I cannot find right now. This information was definitely *wrong*! I am sorry.
The only two means to expose a variable to multiple files (or modules) are to either set it in `module.exports` or to set it in `global`. The latter concept also exists in browser environments, namely under the name `window`. If we ever strive for browser support, we must pay attention to this. Because `global` doesn't exist in browser environments we would need to set global variable `global` to `window`: `window.global = window`.

<hr>
#### Footnotes:

(1) Private variables are a tricky topic in JavaScript, see [Mozilla Developer Network's article on that matter](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Contributor_s_Guide/Private_Properties). Basically, `this.xyz` should be avoided since it can be accessed by everyone. We certainly don't want users to modify or rely on the attributes of a Network object:
 ```
if (myNetwork.queue.length == 0) { ... }
myNetwork.list = null; // this can result in fatal errors
```
@tlrobinson What construct do you usually use for private variables? I'd opt for WeakMaps nowadays.

**Comment by jpaulm** [comment]
Very detailed - thanks so much!  Just verifying... when you say

var fbp = require('fbp');

are you assuming that the jsfbp project has been published to npm under the
name 'fbp'?   If so, what do we do before then?

When you speak of not exposing core classes, I think you mean for network
builders.  For component builders, I would assume you have to expose them -
unless there is some crafty way of hiding them...?

Regards,

Paul

PS I'll look at Travis...

**Comment by ComFreek** [comment]
> are you assuming that the jsfbp project has been published to npm under the
name 'fbp'?   If so, what do we do before then?

Correct! I would solidify the API first, especially the Network part discussed above, but it's totally up to you to decide when we join NPM.

> When you speak of not exposing core classes, I think you mean for network
builders.
Correct! For people who just want to build a network from ready-made components.

>  For component builders, I would assume you have to expose them -
unless there is some crafty way of hiding them...?
Yes, we must expose them unless you want to add another layer of indirection within the API, which would only make everything more complex.

PS: I've just encountered a fork of this project: https://github.com/kenhkan/jsfbp/tree/standalone-runtime, have a look at the big comment in its modified `index.js` (on the branch *standalone-runtime*): https://github.com/kenhkan/jsfbp/blob/standalone-runtime/index.js I still share the view that code maintainability and readability outperform negligible performance differences in most cases. A performance benchmark of the fork would be interesting to see.

**Comment by tlrobinson** [comment]
"Basically, this.xyz should be avoided since it can be accessed by everyone."

I don't agree. I think it's good enough to just document what's public and what's private, or use the convention that properties beginning with "_" should be considered private. Let programmers shoot themselves in the foot if they want to, as long as you're clear when they are doing so.

**Comment by tlrobinson** [comment]
I haven't tried it, but I don't see how @kenhkan's fork retains the synchronous-style of writing components (e.x. `while` loops with synchronous `receive`) and compatibility with asynchronous APIs (e.x. https://github.com/kenhkan/jsfbp/blob/standalone-runtime/components/randdelay.js#L11-L19) without the use of Fibers.

**Comment by kenhkan** [comment]
Woah. Thank you @tlrobinson for mentioning me. I somehow missed this whole thread of useful information!

Let me provide some context for my fork. It actually came about after I'd talked to Paul about noflo, in which I was involved for a while in the early days. For a while I was defending noflo's design decisions because of what I thought were JS' limitations that necessitated the differences. In the end, I decided to experiment with making a fully FBP-compliant implementation in JavaScript. So by no means is everything completely working. In fact, there's a list of TODOs in the preamble.

Having said that, I do want to point out several things:

> I haven't tried it, but I don't see how @kenhkan's fork retains the synchronous-style of writing components (e.x. while loops with synchronous receive) and compatibility with asynchronous APIs (e.x. https://github.com/kenhkan/jsfbp/blob/standalone-runtime/components/randdelay.js#L11-L19) without the use of Fibers.

It doesn't try to. The point is to make component programming as natural to JS programmers as possible, with idiomatic JS. So you still use callbacks (as you rightly pointed out in the modified `randdelay` component). In fact, I would argue that if you only have one level of callback, it's actually a very effective means of asynchronous programming. That's what gives JS its expressiveness and simplicity. Callback hell really requires more than one callback to be hellish. (And with FBP you can be fairly confident that you're doing something wrong if you use more than one callback.)

As a side note, I actually personally prefer synchronous programming style and agree that it is superior (I'm a proud Haskeller myself :D). The problem is that it needs to be handled at the language/VM level; otherwise more likely than not you are going to have a leaky abstraction. Just look at Promises/A+.

> I still share the view that code maintainability and readability outperform negligible performance differences in most cases. A performance benchmark of the fork would be interesting to see.

That is definitely what I value most as well. Actually, it's the whole appeal of FBP to me: being able to write something that I can understand in 6 months. I will actually remove the performance goal from the preamble. The story behind that was more because of the repeated discussions of using WebWorkers (on the client side), forking child processes (on the server side), etc to achieve concurrency between processes ("processes" in the FBP sense). This was the reason why for so long I had thought that true FBP couldn't be implemented in JS, but then I realized that all we needed was concurrency, not so much parallelism. It became the reason why I wanted to experiment with this new runtime.

The goal of "performance" is really just an extension to the first three goals outlined in the preamble: (1) a small runtime, (2) cross-platform, and (3) that users on "legacy" platforms (say, IE11) should be able to use JSFBP.

I only emphasize the "legacy" part because nowadays tech platforms (esp. on the web) only has a shelf life of a year or two. The appeal of FBP to me is that you can just write something and expect it to work for a very long time with minimal maintenance. And given that FBP is a heavily explored concept (and battle-tested in production!), I feel that we should write JSFBP in a stable subset of JS that everyone already agrees on and is unlikely to change in the future to make sure that components (the networks that depend on them) written right now will work reasonably well going forward.

I'd love to know what you guys think is the most important to you when it comes to FBP. And of course, any insight into what else I should look more into would be great as well! :)

**Comment by ComFreek** [comment]
> I don't agree. I think it's good enough to just document what's public and what's private, or use the convention that properties beginning with "_" should be considered private. Let programmers shoot themselves in the foot if they want to, as long as you're clear when they are doing so.
><br>Author: @tlrobinson

Do you share this view with regard to every programming language or just JS? If it's the latter, I can understand your point since it's easier to use `_` than WeakMap. If it's the former, I would like to know why so many languages do have private or protected attributes :)

Re "shoot temselves in the foot": Aren't we shooting ourselves in the foot if we break compatbility with many users? When it comes to upgrading to a new FBP version, I would argue that it's easier to overlook the usage of a private variable (prefixed with `_`) than the usage of monkey patching (which hopefully happens in individual files).

<hr>
@kenhkan randdelay would look like the following, right?
```
waitForPackets(function (ip) {
  if (ip === null) {
    return;
  }
  sleep(proc, Math.random() * intvl, ip, function (ip) {
    outport.send(ip);
  });
});
```

>  (1) a small runtime, (2) cross-platform, and (3) that users on "legacy" platforms (say, IE11) should be able to use JSFBP.
> <br>Author: @kenhkan 

I agree with (2) and (3), but what do you consider a 'small runtime'? Does the use of Fibers (apart from binding it to Node.js) make the current implementation big?

> I feel that we should write JSFBP in a stable subset of JS that everyone already agrees on and is unlikely to change in the future to make sure that components (the networks that depend on them) written right now will work reasonably well going forward.
> <br>Author: @kenhkan 

I agree with this as well, but the adherence to this aim should **not** be as strong as it is in LaTeX for example. Its backwards compatibility enforces some design decisions, which would not be made at the present day.

Do you plan to keep working on your fork? Or have you just done some experimenting to eventually merge it into this repository?

**Comment by kenhkan** [comment]
> @kenhkan randdelay would look like the following, right?
> 
> ```js
> waitForPackets(function (ip) {
>   if (ip === null) {
>     return;
>   }
>   sleep(proc, Math.random() * intvl, ip, function (ip) {
>     outport.send(ip);
>   });
> });
> ```

With the standalone runtime, it doesn't really matter. The queue is fully managed so that the synchronous style of `receive()` that it uses right now does the same thing (side note: most examples in the `examples` directory actually work on this branch). If it were to follow this style that you suggest, we can scrap the `ip` to the `sleep` function given inherent functional scope per IP. So what you suggested may be a better approach. On the other hand, without explicit `receive` we would lose a crucial feature of loopers vs non-loopers in FBP. If there is a way to implement that without looking too awkward, I think your suggestion is syntactically and mentally more appealing to JS programmers.

> (1) a small runtime, (2) cross-platform, and (3) that users on "legacy" platforms (say, IE11) should be able to use JSFBP.
> 
> Author: @kenhkan
> I agree with (2) and (3), but what do you consider a 'small runtime'? Does the use of Fibers (apart from binding it to Node.js) make the current implementation big?

A small runtime so that the user doesn't have to deal with too many moving parts. My personal experience with NPM packages is that there are many black-box modules out there that I have no idea how they work. It's not so much that they are poorly written (though some are), but that JS doesn't provide a good enough debugging environment for someone who didn't write the library (or code in general). So my goal is to limit the number of libraries to 1. It's not to say that users shouldn't use libraries at all. It's just that JSFBP, as a library, shouldn't add yet another layer of abstraction beneath it if it's not necessary.

> I feel that we should write JSFBP in a stable subset of JS that everyone already agrees on and is unlikely to change in the future to make sure that components (the networks that depend on them) written right now will work reasonably well going forward.
> 
> Author: @kenhkan
> I agree with this as well, but the adherence to this aim should not be as strong as it is in LaTeX for example. Its backwards compatibility enforces some design decisions, which would not be made at the present day.

I agree. I don't think we should adhere to ES4 and support IE6. You'd know you're talking to someone crazy otherwise. :) That aim is more as a general guideline. Personally I absolutely hate rapidly changing software, especially a library or a platform that my code in PRODUCTION depends on. Yes, of course I can choose not to upgrade, but I do expect patches and support within a reasonable timeframe, especially from a responsible open-source project. I think that FBP is fairly well-defined at this point and that performance is good enough right now and can always be improved later on (to your point in an earlier post) that there isn't a strong need to use something more than ES5 at this point.

> Do you plan to keep working on your fork? Or have you just done some experimenting to eventually merge it into this repository?

Yea, I've been talking to Paul for a while. My goal is to at least get this to the point of full FBP compliance with browser side support. What comes after that point is up to the community. I just want to be able to use FBP. haha. Again, it's an experiment, so comments and suggestions are welcomed. :)

**Comment by tlrobinson** [comment]
FYI, I make my case for a Stream-based FBP system here: https://github.com/jpaulm/jsfbp/issues/14#issuecomment-74738438

I suggest we move this discussion there or somewhere else besides an already merged pull request :)

**Comment by kenhkan** [comment]
:+1: Agreed. Thanks for the note.

I believe the general consensus right now is to replace fibers with another library/framework/feature like generators/streams/etc with a focus of server-side JSFBP (Node.js stream is a fantastic abstraction for a server-side JS implementation!), so I'll continue my fork until it hits a stable milestone before I jump back into the conversation again. :)

**Comment by jpaulm** [comment]
Do streams provide back pressure?

Paul

**Comment by tlrobinson** [comment]
Yes. Streams currently have a ["highWaterMark" property](http://nodejs.org/api/stream.html#stream_new_stream_writable_options), and if more bytes (or objects in object mode) than that are buffered then `write()` will start returning `false`, indicating the producer should stop sending data until the [`drain` event](http://nodejs.org/api/stream.html#stream_event_drain) is fired.

The [`pipe()` method](http://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) automatically handles backpressure as well.

**Comment by jpaulm** [comment]
If write() returns false, can one then dispose of the IP some other way?
How do you suspend - keep trying until you get a true?  Sounds like polling!

**Comment by kenhkan** [comment]
This is actually a much-studied issue in Node.js. To quote the authoritative voice on Node.js stream libraries, [dominictarr](https://github.com/dominictarr/):

> "This is a problem in node streams, pause is only transfered on write, so on a long chain (a.pipe(b).pipe(c)), if c pauses, b will have to write to it to pause, and then a will have to write to b to pause. If b only transforms a's output, then a will have to write to b twice to find out that c is paused."
>
> Source: https://github.com/dominictarr/pull-stream

And that's why he wrote a variety of libraries to deal with the shortcomings of Node.js streams, which is of course still undergoing a lot of changes as it matures, but at least it's native to the platform.

**Pull request merged**
