### PR TITLE
Alternative network defs

### PR DESCRIPTION
**Pull request by jpaulm**
The last commit was trivial but it recreated alternative_network_defs.  Sorry!  Should I bull ahead, or try to back out the last commit - if so, how?!

### CODE REVIEW

**Comment by dancrumb** [comment]
All fixed!

**Comment by jpaulm** [comment]
Thanks a million!  Did I screw up again?!  git pull and git status showing:

C:\Users\Paul\Documents\GitHub\jsfbp [alternative_network_defs ↕ +0 ~10 -0
!2 |
+0 ~0 -0 !2 !]> git pull
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
C:\Users\Paul\Documents\GitHub\jsfbp [alternative_network_defs ↕ +0 ~10 -0
!2 |
+0 ~0 -0 !2 !]> git status
On branch alternative_network_defs
Your branch and 'origin/alternative_network_defs' have diverged,
and have 10 and 20 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

        modified:   .gitignore
        modified:   README.md
        modified:   core/InputPort.js
        modified:   core/OutputPort.js
        modified:   core/Process.js
        modified:   core/trace.js
        modified:   examples/fbptests.sh
        modified:   test/.eslintrc
        modified:   test/core/InputPort.js
        modified:   test/test_helper.js

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   core/runtimes/FiberRuntime/index.js
        both modified:   examples/fbptest05.js

C:\Users\Paul\Documents\GitHub\jsfbp [alternative_network_defs ↕ +0 ~10 -0
!2 |
+0 ~0 -0 !2 !]>

Or should I just kill alternative_network_defs ?  Sorry to be so dense!

Paul

**Comment by dancrumb** [comment]
Not being dense... but yes, that branch is now done, since it is merged to
master.

So.... here are your steps:

git checkout master
git pull --force
git branch -d alternate_network_defs

then, you'll be good to go!

I'm going to shoot you a little git cheatsheet to help - i'll get to that
in the next day or so.

**Comment by jpaulm** [comment]
Sorry, didn't see that - maybe I should have used --force...

Re process scheduling, you may find this helpful (or it will put you to
sleep): https://www.youtube.com/watch?v=-AmzfhV2hIU

Regards,

Paul

**Pull request merged**
