### PR TITLE
Feature/#35

### PR DESCRIPTION
**Pull request by dancrumb**
I know this feature is on hold, but here's the latest PR

### CODE REVIEW

**Comment by jpaulm** [comment]
Sorry, why the new PR...?  TIA

**Comment by dancrumb** [comment]
I should have explained.

For the past few days, I've been working off a fork and generating PRs from that.

That's gotten pretty cumbersome, so I switched to working off this repo. I killed the last PR and recreated it here.

I know that you're looking into #35 and this isn't to chivvy you along... I just wanted to get to a good place for further development.

**Comment by jpaulm** [comment]
I am chugging along with this, but I've had some programming glitches.  Right now, _processes seems to have decided that it is an associative array (?) and various kinds of iteration that I _think_ worked before aren't working now!  I am making progress, but it's a bit slow!  I'm not even sure that JS _has_ associative arrays!  It may be a Java concept!

Assuming I get it working tomorrow, how would you like me to present it to you: by pushing my code to the master (right terminology?) or creating a PR?

Best regards,

Paul

**Comment by dancrumb** [comment]
Hi Paul!

Take whatever time you need. I know that I've been creating PR after PR, but I'm not impatient at all. I'm happy to wait. Also, I'll nudge you if there's anything that's really slowing me down and feels like it ought not to :)

For the record, JS _does_ have associative arrays - that's what objects are. The syntax is simply:

```
var assoc = {
  name: "Dan",
  age: 36,
  home: {
    city: "Chicago",
    state: "IL"
  }
};

var name = assoc.name;
var age = assoc['age'];
var state = assoc.home.state;
```

If `_processes` is still define as `[]` at the top of `Network.js`, then it's still a normal array.

Here's the kicker. If you're iterating over the array like this:

```
for(var i in this._processes) {
    /* ... */
}
```

then you're probably getting indexes out of order and getting method names in the mix. Yuck!

Instead, you can use the basic `for` structure, or you can use:

```
this._processes.forEach(function(process) {
    /*
     * Do something with the process
     * The value of 'this' is the Network
     */
}.bind(this));
```

**Comment by dancrumb** [comment]
As for review, I think the simplest approach is to create a branch and then create a Pull Request. 

If you update master directly, then the review is moot as the "master" (well named, eh?) is updated.

**Comment by jpaulm** [comment]
Hi Dan!  Apologies - I've had to promote a broken version to master - the
eccentricities of JS and Git together are cumulatively too much for my
brain to handle!  :-)

So, the changes I've made are mostly in index.js - and I *think* the
problem is with the variable runtime, which is either picking up the wrong
values or is undefined - depending on the phase of the moon. Take a look at
lines 202, 203 - I am pretty sure 'this' is wrong, but I don't know what I
should be using...  Clearly this chunk of code has to run after the
[s]connect statements have been processed...

I think I fixed the problem with iterating through _processes - although
perhaps not in the most elegant way...  but why did it change so
drastically?!

I regret promoting a broken version (blush!), but I'm hoping you can sort
things out using whatever handy-dandy debugging tools you have!

Thanks (grovel, grovel)!  Off to drown my sorrows!

Paul

PS Why was fiberRunTime used for some global data, and not the Network
object - the latter seems more intuitive!

**Comment by dancrumb** [comment]
So, now that we've merged your changes, is your feeling that this is largely redundant?

**Comment by dancrumb** [comment]
Also, what is the global data in `fiberRunTime` that you're referring to?

**Comment by jpaulm** [comment]
this._queue = [];
  this._count = null;
  this._tracing = false;

in the ctor,

and _runtime a bit later, I think...  In JavaFBP and the implementations of
that time I always used the Network object for these kinds of jobs...
Does the fiberRunTime object make more sense to you?!

I just realized that the old defProc method did a push onto _processes,
whereas now I am doing (or would like to do) an associative set
(this._processes[name]
= proc; ) - maybe this is why I had so much trouble iterating over
_processes!

Regards,

Paul

**Comment by dancrumb** [comment]
I created #62 to address the associative array stuff.

**Comment by dancrumb** [comment]
I think tracing stuff can be handled by the trace function I created. Rather than the runtime having its own internal variable, we can just use the global setting

**Comment by jpaulm** [comment]
Sounds good!  Will you do that?

Thanks,

P.

**Comment by dancrumb** [comment]
Standardized tracing: #64

**Pull request closed without merging**
